export const strings = {
  appName: 'BusLedger',
  greeting: 'Good morning',
  ownerLabel: 'Owner',
  demoBus: 'Your bus will appear here',
  scanSheet: 'Scan collection sheet',
  todayNotLogged: 'Today’s sheet is not logged',
  todayLogged: 'Today’s sheet is logged',
  operatingBalance: 'Operating balance',
  totalCollection: 'Total collection',
  totalExpense: 'Total operating expense',
  daysEntered: 'Days entered',
  monthCalendar: 'Month calendar',
  noSheets: 'No sheets saved for this month',
  noSheetsHelp: 'Scan a collection sheet to begin your ledger.',
  recentSheets: 'Recent sheets',
  currentMonth: 'Records',
  menu: 'Menu',
  home: 'Home',
  scan: 'Scan',
  reports: 'Monthly report',
  foundationBanner: 'Foundation preview — connect Supabase to save your first sheet.',
  configurationNeeded: 'Supabase configuration is needed before sign-in and saving are enabled.',
  close: 'Close',
  loading: 'Loading your BusLedger…',
  signIn: 'Sign in',
  signOut: 'Log out',
  emailAddress: 'Email address',
  password: 'Password',
  newPassword: 'New password',
  confirmPassword: 'Confirm new password',
  forgotPassword: 'Forgot password?',
  resetPassword: 'Reset password',
  resetPasswordHelp: 'Enter your email address and we will send a password-reset link.',
  sendResetLink: 'Send reset link',
  resetLinkSent: 'If that email belongs to the owner account, a reset link is on its way.',
  savePassword: 'Save new password',
  passwordUpdated: 'Your password has been updated. You can now return to BusLedger.',
  backToSignIn: 'Back to sign in',
  setupTitle: 'Set up your bus',
  setupHelp: 'This is the only bus in BusLedger. You can change these details later in Settings.',
  registrationNumber: 'Bus registration number',
  displayName: 'Display name',
  route: 'Route',
  optional: 'Optional',
  saveAndContinue: 'Save and continue',
  settings: 'Bus profile',
  settingsHelp: 'Keep the one bus shown in your ledger accurate.',
  saveChanges: 'Save changes',
  savedChanges: 'Bus profile updated.',
  account: 'Account',
  configurationTitle: 'Connect Supabase first',
  configurationHelp: 'Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to .env.local, then restart the app.',
  retry: 'Try again',
  menuHelp: 'Your bus and account controls.',
  helpSupport: 'Help & support',
  profileLoadErrorTitle: 'We could not load your bus',
  profileLoadErrorHelp: 'Please check your connection and try again.',
  signInProgress: 'Signing in…',
  sendingProgress: 'Sending…',
  savingProgress: 'Saving…',
  passwordLengthError: 'Use at least 8 characters for your password.',
  passwordMatchError: 'The two passwords do not match.',
} as const
